-- AlterTable
ALTER TABLE "Applicant" DROP COLUMN IF EXISTS "workValues",
DROP COLUMN IF EXISTS "teamStyle",
DROP COLUMN IF EXISTS "workEnvironment",
DROP COLUMN IF EXISTS "motivation";

ALTER TABLE "Applicant" ADD COLUMN IF NOT EXISTS "hierarchy" INTEGER,
ADD COLUMN IF NOT EXISTS "autonomy" INTEGER,
ADD COLUMN IF NOT EXISTS "teamwork" INTEGER,
ADD COLUMN IF NOT EXISTS "workStructure" INTEGER,
ADD COLUMN IF NOT EXISTS "feedback" INTEGER,
ADD COLUMN IF NOT EXISTS "flexibility" INTEGER;

-- AlterTable
ALTER TABLE "Job" DROP COLUMN IF EXISTS "workValues",
DROP COLUMN IF EXISTS "teamStyle",
DROP COLUMN IF EXISTS "workEnvironment",
DROP COLUMN IF EXISTS "motivation";

ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "hierarchy" INTEGER,
ADD COLUMN IF NOT EXISTS "autonomy" INTEGER,
ADD COLUMN IF NOT EXISTS "teamwork" INTEGER,
ADD COLUMN IF NOT EXISTS "workStructure" INTEGER,
ADD COLUMN IF NOT EXISTS "feedback" INTEGER,
ADD COLUMN IF NOT EXISTS "flexibility" INTEGER;

